---
systemd:
  units:
    - name: install.service
      enable: true
      contents: |
        [Unit]
        Description=Install Container Linux

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/bash -c 'sed -i "s/PRIVATE_IPV4/$(curl http://169.254.169.254/meta-data/meta-data/local-ipv4)/g" /opt/ignition'
        ExecStart=/usr/bin/bash -c 'sed -i "s/HOSTNAME/$(curl http://169.254.169.254/meta-data/meta-data/hostname)/g" /opt/ignition'
        ExecStart=/usr/bin/coreos-install -d /dev/vda -i /opt/ignition
        ExecStart=/usr/sbin/reboot

        [Install]
        WantedBy=multi-user.target
storage:
  files:
    - path: /opt/ignition
      filesystem: root
      mode: 0644
      contents:
        inline: |
          ${ignition}
